[package]
name = "simple_tree_filesystem"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown = "0.16.0"
lazy_static = "1.5.0"
spinning_top = "0.3.0"
tethys_core = { path = "../tethys_core" }
